---
name: Build Flutter Android APK

'on':
  workflow_dispatch:
  push:
    branches: [android]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Flutter SDK
        run: |
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.0-stable.tar.xz
          tar xf flutter_linux_3.24.0-stable.tar.xz
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
      - name: Print Flutter version
        run: flutter --version
      - name: Print Dart version
        run: flutter/bin/dart --version
      - name: Install dependencies
        run: flutter/bin/dart pub get
      - name: Build Android APK
        run: flutter build apk --release
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
