---
name: Deploy Flutter Web to GitHub Pages

'on':
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.pub-cache
            /home/runner/.cache/flutter
          key: flutter-sdk-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            flutter-sdk-${{ runner.os }}-
      - name: Remove system Dart from PATH
        run: |
          export PATH=$(echo $PATH | tr ':' '\n' | grep -v '/usr/lib/dart/bin' | paste -sd ':' -)
      - name: Upgrade Flutter SDK globally
        run: |
          sudo snap install flutter --classic
          flutter upgrade
      - name: Print Flutter version
        run: flutter --version
      # Flutter is now globally available, no need to force PATH
      - name: Print Dart version (Flutter SDK)
        run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Run Flutter Doctor
        run: flutter doctor -v

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.pub-cache
            /home/runner/.cache/flutter
          key: flutter-sdk-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            flutter-sdk-${{ runner.os }}-
      - name: Remove system Dart from PATH
        run: |
          export PATH=$(echo $PATH | tr ':' '\n' | grep -v '/usr/lib/dart/bin' | paste -sd ':' -)
      - name: Upgrade Flutter SDK globally
        run: |
          sudo snap install flutter --classic
          flutter upgrade
      - name: Print Flutter version
        run: flutter --version
      # Flutter is now globally available, no need to force PATH
      - name: Print Dart version (Flutter SDK)
        run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Build web app
        run: flutter build web --release
