---
name: Deploy Flutter Web to GitHub Pages

'on':
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: actions/setup-flutter@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      - name: Install dependencies
        run: $(dirname $(which flutter))/dart pub get
      - name: Build web app
        run: flutter build web --release
