
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.pub-cache
            /home/runner/.cache/flutter
          key: flutter-sdk-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            flutter-sdk-${{ runner.os }}-
      - name: Remove system Dart from PATH
        run: |
          export PATH=$(echo $PATH | tr ':' '\n' | grep -v '/usr/lib/dart/bin' | paste -sd ':' -)
      - name: Upgrade Flutter SDK globally
        run: |
          sudo snap install flutter --classic
          flutter upgrade
      - name: Print Flutter version
        run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Run Flutter Doctor
        run: flutter doctor -v

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.pub-cache
            /home/runner/.cache/flutter
          key: flutter-sdk-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            flutter-sdk-${{ runner.os }}-
      - name: Remove system Dart from PATH
        run: |
          export PATH=$(echo $PATH | tr ':' '\n' | grep -v '/usr/lib/dart/bin' | paste -sd ':' -)
      - name: Upgrade Flutter SDK globally
        run: |
          sudo snap install flutter --classic
          flutter upgrade
      - name: Print Flutter version
        run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Build web app
        run: flutter build web --release

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Run Flutter Doctor
        run: flutter doctor -v
      - name: Analyze Dart code
        run: flutter analyze
      - name: Check Dart formatting
        run: dart format --set-exit-if-changed .
      - name: Build web app
        run: flutter build web --release
      - name: Check build output
        run: |
          if [ ! -d build/web ]; then
            echo "Web build directory not found!"
            exit 1
          fi
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
